
// This file has been generated by the GUI designer. Do not modify.
namespace clawputked
{
	public partial class MapEditorWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget clawputked.MapEditorWindow
			this.Name = "clawputked.MapEditorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MapEditorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 663;
			this.DefaultHeight = 624;
			this.Show ();
		}
	}
}
